export const Items = [
    {
        id: 1,
        category: 'product',
        productName: 'Office Wear',
        productPrice: 120,
        description: 'reversible angora cardigan',
        productImage: require('../assets/Images/dress1.png'),
    },
    {
        id: 2,
        category: 'product',
        productName: 'Black',
        productPrice: 125,
        description: 'reversible angora cardigan',
        productImage: require('../assets/Images/dress2.png'),
    },
    {
        id: 3,
        category: 'product',
        productName: 'Church Wear',
        productPrice: 105,
        description: 'reversible angora cardigan',
        productImage: require('../assets/Images/dress3.png'),
    },
    {
        id: 4,
        category: 'product',
        productName: 'Lamerei',
        productPrice: 160,
        description: 'reversible angora cardigan',
        productImage: require('../assets/Images/dress4.png'),
      },
      {
        id: 5,
        category: 'product',
        productName: '21WN',
        productPrice: 180,
        description: 'reversible angora cardigan',
        productImage: require('../assets/Images/dress5.png'),
      },
      {
        id: 6,
        category: 'Lopo',
        productName: 'Office Wear',
        productPrice: 150,
        description: 'reversible angora cardigan',
        productImage: require('../assets/Images/dress6.png'),
      },
      {
        id: 7,
        category: '21WN',
        productName: 'Office Wear',
        productPrice: 100,
        description: 'reversible angora cardigan',
        productImage: require('../assets/Images/dress7.png'),
      },
      {
        id: 8,
        category: 'product',
        productName: 'Lame',
        productPrice: 130,
        description: 'reversible angora cardigan',
        productImage: require('../assets/Images/dress3.png'),
      },

  ];